# Makefile generated by Makefile Generator - Made by Dallan Healey 2015 #
all : Game.o maps\Maps.o 
	 gcc Game.o maps\Maps.o 
Game.o : Game.c C:\Users\Dallan\Documents\Projects\C\Game\maps\Maps.h 
	 gcc -c Game.c 
Maps.o : maps\Maps.c maps\Maps.h 
	 gcc -c maps\Maps.c 
